---
- name: ensure clusterconfigs directory exists
  file:
    path: /home/kni/clusterconfigs
    state: directory

- name: create install-config.yaml
  template:
    src: install-config.yaml
    dest: /home/kni/clusterconfigs/install-config.yaml

- name: create hardlink to install-config.yaml
  file:
    path: /home/kni/install-config.yaml
    state: hard
    src: /home/kni/clusterconfigs/install-config.yaml
    force: true

- name: create manifests
  command: >-
    /usr/local/bin/openshift-baremetal-install --dir ~/clusterconfigs create manifests
  args:
    creates: /home/kni/clusterconfigs/manifests

- name: create ignition configs
  command: >-
    /usr/local/bin/openshift-baremetal-install --dir ~/clusterconfigs create ignition-configs
  args:
    creates: /home/kni/clusterconfigs/bootstrap.ign

- name: create baremetal interface config
  delegate_to: localhost
  template:
    src: ifcfg-baremetal
    dest: ./ifcfg-baremetal

- name: base64 encode baremetal interface config
  set_fact:
    ifcfg_baremetal: "{{ lookup('pipe', 'base64 -w0 ifcfg-baremetal') }}"

- name: create ipmi route config
  delegate_to: localhost
  copy:
    content: |
      ADDRESS0={{ os_ipmi_cidr|ipaddr('address') }}
      NETMASK0={{ os_ipmi_cidr|ipaddr('netmask') }}
      GATEWAY={{ os_ipmi_gw }}
    dest: ./route-baremetal

- name: base64 encode baremetal route config
  set_fact:
    route_baremetal: "{{ lookup('pipe', 'base64 -w0 route-baremetal') }}"

- name: generate ignition stanzas
  set_fact:
    ignition_ifcfg_baremetal:
      filesystem: root
      path: /etc/sysconfig/network-scripts/ifcfg-ens3
      contents:
        verification: {}
        source: >-
          data:text/plain;charset=utf-8;base64,{{ ifcfg_baremetal }}
      mode: 420
    ignition_route_baremetal:
      filesystem: root
      path: /etc/sysconfig/network-scripts/route-ens3
      contents:
        verification: {}
        source: >-
          data:text/plain;charset=utf-8;base64,{{ route_baremetal }}
      mode: 420

- name: write ifcfg stanza
  copy:
    content: "{{ ignition_ifcfg_baremetal | to_nice_json }}"
    dest: /home/kni/ignition_ifcfg_baremetal.json

- name: write route stanza
  copy:
    content: "{{ ignition_route_baremetal | to_nice_json }}"
    dest: /home/kni/ignition_route_baremetal.json

# This is, frankly, ridiculous
- name: create updated ignition configuration
  command: >-
    jq -s '
    .[1] as $ifcfg
    | .[2] as $route
    | .[0]
    | .storage.files[.storage.files|length]
    |= . + $ifcfg
    | .storage.files[.storage.files|length]
    |= . + $route
    '
    /home/kni/clusterconfigs/bootstrap.ign
    /home/kni/ignition_ifcfg_baremetal.json
    /home/kni/ignition_route_baremetal.json
  register: ign_bootstrap

- name: replace ignition configuration
  copy:
    content: "{{ ign_bootstrap.stdout }}"
    dest: /home/kni/clusterconfigs/bootstrap.ign
