---
- include_role:
    name: pull-secret

- name: ensure clusterconfigs directory exists
  file:
    path: /home/kni/clusterconfigs
    state: directory

- name: create install-config.yaml
  template:
    src: install-config.yaml
    dest: /home/kni/clusterconfigs/install-config.yaml

- name: create hardlink to install-config.yaml
  file:
    path: /home/kni/install-config.yaml
    state: hard
    src: /home/kni/clusterconfigs/install-config.yaml
    force: true

- name: create manifests
  command: >-
    /usr/local/bin/openshift-baremetal-install --dir ~/clusterconfigs create manifests
  args:
    creates: /home/kni/clusterconfigs/manifests
