namespace: metallb-system

resources:
  - github.com/metallb/metallb//manifests?ref=v0.9.3
  - clusterrole.yml
  - rolebinding.yml

patches:
  - target:
      kind: Deployment
      name: controller
    patch: |-
      - op: remove
        path: /spec/template/spec/securityContext/runAsUser
