---
all:
  children:
    nameservers:
      hosts:
        ns1:
          ansible_host: 128.31.28.136
        ns2:
          ansible_host: 128.31.28.224
      vars:
        ansible_user: cloud-user
    provisioner:
      vars:
        ansible_user: kni
      hosts:
        provisioner.cnv.massopen.cloud:
          ipmi_host: 10.0.17.25
    openshift:
      vars:
        ansible_python_interpreter: /usr/libexec/platform-python
      children:
        managers:
          hosts:
            openshift-master-0.cnv.massopen.cloud:
              ipmi_host: 10.0.17.34
              public_ip: 128.31.28.3
              provisioning_mac: 00:0f:53:0d:7b:84
              baremetal_mac: 00:0f:53:0d:7b:85
            openshift-master-1.cnv.massopen.cloud:
              ipmi_host: 10.0.3.13
              public_ip: 128.31.28.4
              provisioning_mac: 00:0f:53:0c:46:a0
              baremetal_mac: 00:0f:53:0c:46:a1
            openshift-master-2.cnv.massopen.cloud:
              ipmi_host: 10.0.5.12
              public_ip: 128.31.28.5
              provisioning_mac: 00:0f:53:0d:b3:1c
              baremetal_mac: 00:0f:53:0d:b3:1c
        workers:
          hosts:
            openshift-worker-0.cnv.massopen.cloud:
              ipmi_host: 10.0.17.39
              public_ip: 128.31.28.10
              provisioning_mac: 00:0f:53:0d:f7:29
              baremetal_mac: 00:0f:53:0d:f7:30
            openshift-worker-1.cnv.massopen.cloud:
              ipmi_host: 10.0.3.12
              public_ip: 128.31.28.11
              provisioning_mac: 00:0f:53:0d:b3:41
              baremetal_mac: 00:0f:53:0d:b3:42
#           openshift-worker-2.cnv.massopen.cloud:
#             ipmi_host: 10.0.17.35
#             provisioning_mac: 00:0f:53:0c:45:79
#             baremetal_mac: 00:0f:53:0c:45:80
    openshift_ipmi:
      hosts:
        10.0.17.34:
        10.0.17.39:
        10.0.3.13:
        10.0.3.12:
        10.0.5.12:
#       10.0.17.35:
