---
all:
  children:
    provisioner:
      vars:
        ansible_user: kni
      hosts:
        provisioner.cnv.massopen.cloud:
          ipmi_host: 10.0.17.25
    openshift:
      children:
        managers:
          hosts:
            openshift-master-0.cnv.massopen.cloud:
              ipmi_host: 10.0.17.34
              provisioning_mac: 00:0f:53:0d:7b:85
            openshift-master-1.cnv.massopen.cloud:
              ipmi_host: 10.0.3.13
              provisioning_mac: 00:0f:53:0c:46:a1
            openshift-master-2.cnv.massopen.cloud:
              ipmi_host: 10.0.5.12
              provisioning_mac: 00:0f:53:0d:b3:1d
        workers:
          hosts:
            openshift-worker-0.cnv.massopen.cloud:
              ipmi_host: 10.0.17.39
              provisioning_mac: 00:0f:53:0d:f7:29
            openshift-worker-1.cnv.massopen.cloud:
              ipmi_host: 10.0.3.12
              provisioning_mac: 00:0f:53:0d:b3:41
#           openshift-worker-2.cnv.massopen.cloud:
#             ipmi_host: 10.0.17.35
#             provisioning_mac: 00:0f:53:0c:45:79
    openshift_ipmi:
      hosts:
        10.0.17.34:
        10.0.17.39:
#       10.0.17.35:
        10.0.3.13:
        10.0.3.12:
        10.0.5.12:
