---
all:
  children:
    provisioner:
      vars:
        ansible_user: kni
      hosts:
        neu-17-25.maas.massopen.cloud:
          ipmi_host: 10.0.17.25
    openshift:
      children:
        managers:
          hosts:
            neu-17-34.maas.massopen.cloud:
              ipmi_host: 10.0.17.34
              provisioning_mac: 00:0f:53:0d:7b:85
            neu-3-13.maas.massopen.cloud:
              ipmi_host: 10.0.3.13
              provisioning_mac: 00:0f:53:0c:46:a1
            neu-5-12.maas.massopen.cloud:
              ipmi_host: 10.0.5.12
              provisioning_mac: 00:0f:53:0d:b3:1d
        workers:
          hosts:
            neu-17-39.maas.massopen.cloud:
              ipmi_host: 10.0.17.39
              provisioning_mac: 00:0f:53:0d:f7:29
            neu-3-12.maas.massopen.cloud:
              ipmi_host: 10.0.3.12
              provisioning_mac: 00:0f:53:0d:b3:41
#           neu-17-35.maas.massopen.cloud:
#             ipmi_host: 10.0.17.35
#             provisioning_mac: 00:0f:53:0c:45:79
    openshift_ipmi:
      hosts:
        10.0.17.34:
        10.0.17.39:
        10.0.17.35:
        10.0.3.13:
        10.0.3.12:
        10.0.5.12:
