---
all:
  children:
    nameservers:
      hosts:
        cnv-dhcp1.massopen.cloud:
        cnv-dhcp2.massopen.cloud:
      vars:
        ansible_user: root
    provisioner:
      vars:
        ansible_user: kni
        manage_dns: true
      hosts:
        provisioner.cnv.massopen.cloud:
          hil_node: neu-17-25
          ipmi_host: "10.0.17.25"
          baremetal_ip: "192.12.185.103/24"
          baremetal_mac: "90:e2:ba:82:35:c8"
          pxe: false
    openshift:
      vars:
        ansible_python_interpreter: /usr/libexec/platform-python
        ansible_user: core
        manage_dns: true
      children:
        managers:
          hosts:
            os-mgr-0.cnv.massopen.cloud:
              hil_node: neu-17-34
              ipmi_host: "10.0.17.34"
              baremetal_ip: "192.12.185.110/24"
              provisioning_mac: "00:0f:53:0d:7b:84"
              baremetal_mac: "00:0f:53:0d:7b:85"
            os-mgr-1.cnv.massopen.cloud:
              hil_node: neu-3-13
              ipmi_host: "10.0.3.13"
              baremetal_ip: "192.12.185.111/24"
              provisioning_mac: "00:0f:53:0c:46:a0"
              baremetal_mac: "00:0f:53:0c:46:a1"
            os-mgr-2.cnv.massopen.cloud:
              hil_node: neu-5-12
              ipmi_host: "10.0.5.12"
              baremetal_ip: "192.12.185.112/24"
              provisioning_mac: "00:0f:53:0d:b3:1c"
              baremetal_mac: "00:0f:53:0d:b3:1d"
        workers:
          hosts:
            os-wrk-0.cnv.massopen.cloud:
              hil_node: neu-17-39
              ipmi_host: "10.0.17.39"
              baremetal_ip: "192.12.185.115/24"
              provisioning_mac: "00:0f:53:0d:f7:28"
              baremetal_mac: "00:0f:53:0d:f7:29"
            os-wrk-1.cnv.massopen.cloud:
              hil_node: neu-3-12
              ipmi_host: "10.0.3.12"
              baremetal_ip: "192.12.185.116/24"
              provisioning_mac: "00:0f:53:0d:b3:40"
              baremetal_mac: "00:0f:53:0d:b3:41"
            os-wrk-2.cnv.massopen.cloud:
              hil_node: neu-17-35
              ipmi_host: "10.0.17.35"
              baremetal_ip: "192.12.185.117/24"
              provisioning_mac: "00:0f:53:0c:45:78"
              baremetal_mac: "00:0f:53:0c:45:79"
