---
- hosts: provisioner
  become: true
  tags: [fetch]
  tasks:
    # Save a copy of the generated install-config.yaml file for
    # diagnostic/debugging purposes.
    - name: get install-config
      fetch:
        src: /home/kni/install-config.yaml
        dest: cluster/install-config.yaml
        flat: true

    # Fetch the kubeconfig file
    - name: get kubeconfig
      fetch:
        src: /home/kni/clusterconfigs/auth/kubeconfig
        dest: cluster/kubeconfig
        flat: true

    # Fetch the kubeadmin password
    - name: get kubeadmin password
      fetch:
        src: /home/kni/clusterconfigs/auth/kubeadmin-password
        dest: cluster/kubeadmin-password
        flat: true

- hosts: localhost
  tags: [ocp]
  environment:
    KUBECONFIG: ./cluster/kubeconfig
  roles:
    # Set up the default ingress certificate (used e.g. for the 
    # openshift web ui).
    - role: ocp/tls

    # Connect OpenShift to the MOC SSO environment.
    - role: ocp/moc-sso

    # Install CNV operator.
    - role: ocp/cnv

    # Configure bridge to permit CNV VMs to connect directly to
    # baremetal network.
    - role: ocp/public-net

    # Configure the hostpath provisioner.
    - role: ocp/hostpath

    # Install metallb load balancer
    - role: ocp/metallb
