---
# Install ssh keys into the `core` user account on all hosts in the
# openshift cluster.
- hosts: provisioner:openshift
  gather_facts: false
  become: true
  tasks:
    - authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ item }}"
      loop: "{{ os_authorized_keys }}"
