---
# Create the certificate authority in a local directory.
- hosts: localhost
  tags: [ca]
  roles:
    - certificate-authority

# Generate certificates
- hosts: localhost
  tags: [certs]
  tasks:
    - name: generate server certificate
      include_role:
        name: certificate-authority
        tasks_from: certificate
      vars:
        crt_name: conserver

    - name: generate user certificates
      include_role:
        name: certificate-authority
        tasks_from: certificate
      loop: "{{ conserver_user_certs }}"
      loop_control:
        loop_var: crt_name

# Install and configure conserver
- hosts: nameservers[0]
  tags: [conserver]
  become: true
  roles:
    - console-server
