---
- hosts: storage
  gather_facts: false
  environment:
    KUBECONFIG: ./cluster/kubeconfig
  roles:
    - role: ocp/bmh
  
- hosts: localhost
  gather_facts: false
  environment:
    KUBECONFIG: ./cluster/kubeconfig
  roles:
    - role: ocp/lso
    - role: ocp/ocs
