---
- hosts: storage
  gather_facts: false
  environment:
    KUBECONFIG: ./cluster/kubeconfig
  roles:
    - role: ocp/bmh
      tags: [bmh]
  
- hosts: localhost
  gather_facts: false
  environment:
    KUBECONFIG: ./cluster/kubeconfig
  roles:
    - role: ocp/lso
      tags: [lso]

    - role: ocp/ocs
      tags: [ocs]
