---
- name: wait for machineconfig update to start
  when: machineconfig_result is changed
  k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: machineconfigpool
    name: "{{ machineconfig_pool }}"
  register: mcupdate
  until: >-
    mcpupdate.resources is defined and
    mcupdate.resources.0.status.conditions[-1].type == "Updating" and
    mcupdate.resources.0.status.conditions[-1].status == "True"
  retries: "{{ machineconfig_wait_retries }}"
  delay: "{{ machineconfig_wait_delay }}"

- name: wait for machineconfig update to complete
  k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: machineconfigpool
    name: "{{ machineconfig_pool }}"
  register: mcupdate
  until: >-
    mcupdate.resources.0.status.conditions[-1].type == "Updating" and
    mcupdate.resources.0.status.conditions[-1].status == "False"
  retries: "{{ machineconfig_wait_retries }}"
  delay: "{{ machineconfig_wait_delay }}"
