---
- name: ensure local-storage namespace exists
  k8s:
    name: local-storage
    kind: Namespace
    state: present
    api_version: v1

- name: ensure local-storage operator group exists
  k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: local-storage-operator-group
        namespace: local-storage
      spec:
        targetNamespaces:
          - local-storage

- name: subscribe to lso operator
  k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: local-storage-operator
        namespace: local-storage
      spec:
        channel: "{{ lso_channel_version|string }}"
        installPlanApproval: Automatic
        name: local-storage-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: wait for operator installation to complete
  include_role:
    name: ocp/api
    tasks_from: waitfordeployment.yml
  vars:
    deployment_ns: local-storage

# This was a clever idea but it turned out to be useless. LSO doesn't
# recognize the symlink as a valid block device (probably because it
# is inspecting the output of `lsblk` rather than just doing what the
# operator requested).
- name: create lso udev rules
  when: false
  k8s:
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      metadata:
        name: 60-lso-udev-rules
        labels:
          machineconfiguration.openshift.io/role: worker
      spec:
        config:
          ignition:
            version: 2.2.0
          storage:
            files:
              - filesystem: root
                path: /etc/udev/rules.d/60-lso-udev.rules
                contents:
                  source: "{{ lookup('file', '60-lso-udev.rules') | moc.cnv_common.ignition_encode }}"
                mode: 0644

- name: create local storage provisioner
  when: lso_devices is defined
  k8s:
    state: present
    definition:
      apiVersion: "local.storage.openshift.io/v1"
      kind: "LocalVolume"
      metadata:
        name: "local-disks"
        namespace: "local-storage"
      spec:
        nodeSelector:
          nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
        storageClassDevices:
          - storageClassName: "local-storage-class"
            volumeMode: Filesystem
            fsType: xfs
            devicePaths: "{{ lso_devices }}"
