# See https://docs.openshift.com/container-platform/4.5/security/certificates/replacing-default-ingress-certificate.html

---
- name: create tls secret
  k8s:
    state: present
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: default-ingress-certificate
        namespace: openshift-ingress
      data:
        tls.crt: "{{ default_ingress_crt|b64encode }}"
        tls.key: "{{ default_ingress_key|b64encode }}"
      type: kubernetes.io/tls

- name: configure ingress controller
  k8s:
    state: present
    definition:
      apiVersion: operator.openshift.io/v1
      kind: IngressController
      metadata:
        name: default
        namespace: openshift-ingress-operator
      spec:
        defaultCertificate:
          name: default-ingress-certificate
