apiVersion: v1
baseDomain: {{ os_base_domain.split('.', 1).1 }}
metadata:
  name: {{ os_base_domain.split('.').0 }}
networking:
  machineCIDR: {{ os_public_cidr }}
  networkType: OVNKubernetes
compute:
- name: worker
  replicas: 2
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIP: {{ os_vip_api }}
    ingressVIP: {{ os_vip_ingress }}
    dnsVIP: {{ os_vip_dns }}
    provisioningNetworkInterface: "{{ os_prov_interface }}"
    provisioningNetworkCIDR: {{ os_prov_cidr }}
    provisioningBridge: provisioning
{% if os_bootstraposimage is defined %}
    bootstrapOSImage: "{{ os_bootstraposimage }}"
{% endif %}
    hosts:
{% for host in groups.managers %}
      - name: os-mgr-{{ loop.index0 }}
        role: master
        bmc:
          address: ipmi://{{ hostvars[host].ipmi_host }}
          username: {{ os_ipmi_user }}
          password: {{ os_ipmi_password }}
        bootMACAddress: {{ hostvars[host].provisioning_mac }}
        hardwareProfile: default
{% endfor %}
{% for host in groups.workers %}
      - name: os-wrk-{{ loop.index0 }}
        role: worker
        bmc:
          address: ipmi://{{ hostvars[host].ipmi_host }}
          username: {{ os_ipmi_user }}
          password: {{ os_ipmi_password }}
        bootMACAddress: {{ hostvars[host].provisioning_mac }}
        hardwareProfile: unknown
{% endfor %}
pullSecret: >-
  {{ pull_secret | to_json }}
sshKey: >-
  {{ os_public_key }}
imageContentSources:
- mirrors:
  - provisioner.cnv.massopen.cloud:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - provisioner.cnv.massopen.cloud:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
additionalTrustBundle: |
{{ lookup('file', 'domain.crt') | indent(width=2, first=True) }}
