apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/operate-first/continuous-deployment/manifests/overlays/moc-cnv?ref=v1.8.3-2
  - operate-first-app-of-apps.yaml

patchesJson6902:
  - target:
      kind: ConfigMap
      name: argocd-cm
      version: v1
    patch: |
      - op: replace
        path: /data/url
        value: https://argocd-server-argocd.apps.cnv.massopen.cloud
