---
- name: ensure openshift-cnv namespace exists
  k8s:
    name: openshift-cnv
    kind: Namespace
    state: present
    api_version: v1

- name: subscribe to cnv operator
  k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: kubevirt-hyperconverged
        namespace: openshift-cnv
      spec:
        channel: "{{ cnv_channel_version|string }}"
        installPlanApproval: Automatic
        name: kubevirt-hyperconverged
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        startingCSV: "{{ cnv_version }}"

- name: wait for operator installation to complete
  include_role:
    name: ocp/api
    tasks_from: waitforsubscription.yml
  vars:
    operator_ns: openshift-cnv
    operator_name: kubevirt-hyperconverged

- name: create cnv operator deployment
  k8s:
    state: present
    definition:
      apiVersion: hco.kubevirt.io/v1alpha1
      kind: HyperConverged
      metadata:
        name: kubevirt-hyperconverged
        namespace: openshift-cnv
      spec: {}
