---
- name: register system with redhat
  redhat_subscription:
    state: present
    username: "{{ rh_username }}"
    password: "{{ rh_password }}"
    auto_attach: "{{ rh_auto_attach }}"
    pool_ids: "{{ rh_pools }}"

- name: enable repositories
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop: "{{ rh_repositories }}"
