---
- name: create ipmi secrets for storage nodes
  delegate_to: localhost
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ inventory_hostname.split('.')[0] }}-bmc-secret"
        namespace: openshift-machine-api
      type: Opaque
      data:
        password: "{{ os_ipmi_password|b64encode }}"
        username: "{{ os_ipmi_user|b64encode }}"

- name: create bmh objects for openshift nodes
  delegate_to: localhost
  k8s:
    state: present
    definition:
      apiVersion: metal3.io/v1alpha1
      kind: BareMetalHost
      metadata:
        name: "{{ inventory_hostname.split('.')[0] }}"
        namespace: openshift-machine-api
      spec:
        online: true
        bmc:
          address: "ipmi://{{ ipmi_host }}"
          credentialsName: "{{ inventory_hostname.split('.')[0] }}-bmc-secret"
        bootMACAddress: "{{ provisioning_mac }}"
        image:
          checksum: "{{ os_image_checksum_url }}"
          url: "{{ os_image_url }}"
        userData:
          name: "{{ os_role }}-user-data"
          namespace: openshift-machine-api
