---
- name: create ipmi secrets for openshift nodes
  tags: [bmh.secret]
  delegate_to: localhost
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ inventory_hostname.split('.')[0] }}-bmc-secret"
        namespace: openshift-machine-api
      type: Opaque
      stringData:
        password: "{{ os_ipmi_password }}"
        username: "{{ os_ipmi_user }}"

- name: create bmh objects for openshift nodes
  delegate_to: localhost
  k8s:
    state: present
    definition:
      apiVersion: metal3.io/v1alpha1
      kind: BareMetalHost
      metadata:
        name: "{{ inventory_hostname.split('.')[0] }}"
        namespace: openshift-machine-api
      spec:
        online: "{{ bmh_online|default(true)|bool }}"
        bmc:
          address: "ipmi://{{ ipmi_host }}"
          credentialsName: "{{ inventory_hostname.split('.')[0] }}-bmc-secret"
          disableCertificateVerification: true
        bootMACAddress: "{{ provisioning_mac }}"
        hardwareProfile: "{{ os_hardware_profile|default(omit) }}"
