---
- name: open firewall (services)
  become: true
  firewalld:
    zone: public
    service: "{{ item }}"
    state: enabled
    permanent: true
  loop: "{{ provisioner_services }}"

- name: open firewall (ports)
  become: true
  firewalld:
    zone: public
    port: "{{ item }}"
    state: enabled
    permanent: true
  loop: "{{ provisioner_ports }}"
