---
- name: check if provisioning interface exists
  command: >-
    nmcli con show provisioning
  register: check_con_prov
  failed_when: false
  changed_when: check_con_prov.rc != 0

- name: configure provisioning interface
  when: check_con_prov is changed or force_net_reconfigure|default(false)|bool
  shell: |
    set -e

    # delete system interfaces
    nmcli con down "System {{ prov_nic_provision }}" || :
    nmcli con delete "System {{ prov_nic_provision }}" || :

    # delete bridge in case we are reconfiguring
    nmcli con down provisioning || :
    nmcli con delete provisioning || :
    nmcli con down bridge-slave-{{ prov_nic_provision }} || :
    nmcli con delete bridge-slave-{{ prov_nic_provision }} || :

    nmcli con add type bridge \
      ifname provisioning \
      con-name provisioning \
      ipv4.address {{ os_prov_cidr|ipaddr(1)|ipaddr('host/prefix') }} ipv4.method manual \
      ipv6.addresses fd00:1101::1/64 ipv6.method manual
    nmcli con add type bridge-slave \
      ifname "{{ prov_nic_provision }}" \
      con-name "bridge-slave-{{ prov_nic_provision }}" \
      master provisioning
    nmcli con down provisioning
    nmcli con up provisioning
