---
- name: check if provisioning interface exists
  become: true
  command: >-
    nmcli con show provisioning
  register: check_nic_prov
  failed_when: false
  changed_when: check_nic_prov.rc != 0

- name: configure provisioning interface
  when: check_nic_prov is changed
  become: true
  shell: |
    set -e
    nmcli con down "System {{ prov_nic_provision }}" || :
    nmcli con delete "System {{ prov_nic_provision }}" || :
    nmcli con add ifname provisioning type bridge con-name provisioning
    nmcli con add type bridge-slave ifname "{{ prov_nic_provision }}" master provisioning
    nmcli con modify provisioning ipv6.addresses fd00:1101::1/64 ipv6.method manual
    nmcli con down provisioning
    nmcli con up provisioning

