---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 50-set-selinux-for-hostpath-provisioner
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 2.2.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Set SELinux chcon for hostpath provisioner
            Before=kubelet.service

            [Service]
            Type=oneshot
            Environment=HOSTPATH_PROVISIONER_DIR=/srv/local-storage
            ExecStart=/usr/bin/mkdir -m 755 -p $HOSTPATH_PROVISIONER_DIR
            ExecStart=/usr/bin/chcon -Rt container_file_t $HOSTPATH_PROVISIONER_DIR

            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: hostpath-provisioner.service
