---
- name: create machineconfig to manage hostpath provisioner directory
  k8s:
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      metadata:
        name: 50-set-selinux-for-hostpath-provisioner
        labels:
          machineconfiguration.openshift.io/role: worker
      spec:
        config:
          ignition:
            version: 2.2.0
          systemd:
            units:
              - contents: |
                  [Unit]
                  Description=Set SELinux chcon for hostpath provisioner
                  Before=kubelet.service

                  [Service]
                  Type=oneshot
                  ExecStart=/usr/bin/mkdir -m 755 -p {{ hostpath_dir }}
                  ExecStart=/usr/bin/chcon -Rt container_file_t {{ hostpath_dir }}

                  [Install]
                  WantedBy=multi-user.target
                enabled: true
                name: hostpath-provisioner.service
  register: machineconfig

- name: wait for machineconfig update to start
  when: machineconfig is changed
  k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: machineconfigpool
    name: worker
  register: worker
  until: >-
    worker.resources.0.status.conditions[-1].type == "Updating" and
    worker.resources.0.status.conditions[-1].status == "True"
  delay: 10
  retries: 3

- name: wait for machineconfig update to complete
  k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: machineconfigpool
    name: worker
  register: worker
  until: >-
    worker.resources.0.status.conditions[-1].type == "Updating" and
    worker.resources.0.status.conditions[-1].status == "False"
  delay: 10
  retries: 180

- name: create hostpath provisioner deployment
  k8s:
    state: present
    definition:
      apiVersion: hostpathprovisioner.kubevirt.io/v1alpha1
      kind: HostPathProvisioner
      metadata:
        name: hostpath-provisioner
      spec:
        imagePullPolicy: IfNotPresent
        pathConfig:
          path: "{{ hostpath_dir }}"
          useNamingPrefix: "false"

- name: create hostpath provisioner storage class
  k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: hostpath-provisioner
      provisioner: kubevirt.io/hostpath-provisioner
      reclaimPolicy: Delete
      volumeBindingMode: WaitForFirstConsumer
