---
- name: ensure groups exist
  k8s:
    state: present
    definition:
      apiVersion: user.openshift.io/v1
      kind: Group
      metadata:
        name: "{{ item }}"
  loop:
    - approved-users
    - cluster-admins

- name: populate groups if we have a list of users
  k8s:
    state: present
    definition:
      apiVersion: user.openshift.io/v1
      kind: Group
      metadata:
        name: "{{ item }}"
      users: "{{ openshift_users[item] }}"
  when: item in openshift_users|default([])
  loop:
    - approved-users
    - cluster-admins

- name: ensure nad-view-user role exists
  k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        annotations:
          openshift.io/description: >-
            A user that can get basic information about
            network-attachment-definitions.
        name: nad-view-user
      rules:
        - apiGroups:
            - k8s.cni.cncf.io
          resources:
            - network-attachment-definitions
          verbs:
            - list
            - get
            - watch

- name: grant cluster-admin role to members of cluster-admins
  k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: cluster-admins-rb
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: cluster-admins

- name: grant self-provisioner role to members of approved-users
  k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: self-provisioners
        annotations:
          rbac.authorization.kubernetes.io/autoupdate: "false"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: self-provisioner
      subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: approved-users

- name: allow approved users to view network attachment definitions
  k8s:
    state: present
    definition:
      kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: allow-view-nads
        annotations:
          openshift.io/description: >-
            Permit members of the approved-users group to view network
            attachment definitions by binding them to the
            nad-view-user role.
      subjects:
        - kind: Group
          apiGroup: rbac.authorization.k8s.io
          name: approved-users
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: nad-view-user
